#!/bin/bash

rm test.db

sqlite3 test.db <<ENDSQL
CREATE TABLE Persons (
    PersonID INTEGER PRIMARY KEY AUTOINCREMENT,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255),
    Age INTEGER
);
ENDSQL